project_id = "fjekjutzxzvkfzybwhac"

[functions.analyze-prompt]
verify_jwt = true

[functions.generate-bot]
verify_jwt = true

[functions.validate-telegram-token]
verify_jwt = true

[functions.telegram-bot-runtime]
verify_jwt = false

[functions.setup-webhook]
verify_jwt = true

[functions.suggest-commands]
verify_jwt = true

[functions.generate-response]
verify_jwt = true

[functions.bot-assistant]
verify_jwt = true

[functions.ai-bot-builder]
verify_jwt = true

[functions.intelligent-response]
verify_jwt = false

[functions.payment-processor]
verify_jwt = false

[functions.subscription-manager]
verify_jwt = true

[functions.api-executor]
verify_jwt = false